name: CI/CD
on:
  push:
    branches: [ main ]
jobs:
  tests:
    runs-on: ubuntu-latest

    env:
      CONNECTION_URL: ${{ secrets.CONNECTION_URL }}

    steps:
      # Checkout the Repo
      - uses: actions/checkout@v2

      # Install Node 12
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      # Install dependencies
      - run: npm install

      # Run tests
      - run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
  
  CodeScan:
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
        -   name: Checkout repository
            uses: actions/checkout@v3
        -   name: Cache files
            uses: actions/cache@v3
            with:
                path: |
                    ~/.sonar
                key: ${{ runner.os }}-sonar
                restore-keys: ${{ runner.os }}-sonar
        -   name: Run Analysis
            uses: codescan-io/codescan-scanner-action@5b2e8c5683ef6a5adc8fa3b7950bb07debccce12
            with:
                login: ${{ secrets.CODESCAN_AUTH_TOKEN }}
                organization: ${{ secrets.CODESCAN_ORGANIZATION_KEY }}
                projectKey: ${{ secrets.CODESCAN_PROJECT_KEY }}
        -   name: Upload SARIF file
            uses: github/codeql-action/upload-sarif@v2
            with:
                sarif_file: codescan.sarif