name: CI/CD
on:
  push:
    branches: [ main ]
jobs:
  tests:
    name: test
    needs: [ESlint]
    runs-on: ubuntu-latest

    env:
      CONNECTION_URL: ${{ secrets.CONNECTION_URL }}

    steps:
      # Checkout the Repo
      - uses: actions/checkout@v2

      # Install Node 12
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      # Install dependencies
      - run: npm install

      # Run tests
      - run: npm test

    outputs:
      test-status: ${{ job.status }}

  ESlint:
    name: eslint
    runs-on: ubuntu-latest

    env:
      CONNECTION_URL: ${{ secrets.CONNECTION_URL }}

    steps:
      # Checkout the Repo
      - uses: actions/checkout@v2

      # Install Node 12
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      # Install dependencies
      - run: npm install

      # Run tests
      - run: npm run lint

    outputs:
      eslint-status: ${{ job.status }}



    
          

  email:
    runs-on: ubuntu-latest
    #needs: [deploy]
    if: always()
    steps:
      - uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          # user credentials
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          # email subject
          subject: Worflow notify
          # email body as text
          body:  ${{needs.tests.outputs.test-status}} ${{needs.eslint.outputs.eslint-status}}
          # comma-separated string, send email to
          to: ${{ secrets.EMAIL_TO_USERNAME }}
          # from email name
          from: Action notify