name: CI/CD
on:
  push:
    branches: [ main ]
jobs:
  tests:
    name: test
    needs: [ESlint]
    runs-on: ubuntu-latest

    env:
      CONNECTION_URL: ${{ secrets.CONNECTION_URL }}

    steps:
      # Checkout the Repo
      - uses: actions/checkout@v2

      # Install Node 12
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      # Install dependencies
      - run: npm install

      # Run tests
      - run: npm test

  ESlint:
    name: eslint
    runs-on: ubuntu-latest

    env:
      CONNECTION_URL: ${{ secrets.CONNECTION_URL }}

    steps:
      # Checkout the Repo
      - uses: actions/checkout@v2

      # Install Node 12
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      # Install dependencies
      - run: npm install

      # Run tests
      - run: npm run lint


  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          

  email:
    runs-on: ubuntu-latest
    needs: [deploy]
    if: always()
    steps:
      - uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          # user credentials
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          # email subject
          subject: Worflow notify
          # email body as text
          # 
          body: el resultado de los jobs fue el siguiente, Deploy = ${{deploy.result}}, Test = ${{test.result}}, Analisis de codigo = ${{eslint.result}}
          # comma-separated string, send email to
          to: ${{ secrets.EMAIL_TO_USERNAME }}
          # from email name
          from: Action notify